### ISSUE TITLE
Extension activates but doesn't provide LSP functionality when NodeJS installed by asdf

### ISSUE THREAD

**Issue by alex-ketch** [apexskier/nova-typescript#84]
**To reproduce**

1. Create a new TypeScript project (just a `tsconfig.json` and an `index.ts`)
2. Write incorrect TS code
3. _Nothing happens…_ 🦗

_This was experience with the extension provided TS server, as well as one installed in the project directory._

**Expected behavior**

Extension should interface with the LSP, validating code, returning code suggestions, etc.

**Screenshots**

![Screenshot 2020-09-22 at 18 08 46@2x](https://user-images.githubusercontent.com/1646307/93942784-19ec5480-fcff-11ea-9a2f-0d655042955f.png)

**Environment**

- Nova version: 1.1 204636 (Beta with LSP crash fix)
- Extension version: 1.7.0
- TypeScript version: 4.0.3
- Sidebar information: Status: Running, TypeScript: Version 4.0.2
- macOS version: 10.15.6
- NodeJS information:
  - node version: v14.11.0
  - npm version: 6.14.8
  - installation method: [asdf](https://github.com/asdf-vm/asdf)

**Extension console output**

```sh
TypeScript[18:04:47.491000] activating...
TypeScript[18:04:49.579000] using tslib at: /Users/ketch/Work/test/node_modules/typescript/lib
TypeScript[18:04:49.593000] activated
```

**Additional context**

This is a continuation of https://github.com/apexskier/nova-typescript/issues/59
I've tried installing and [running the extension locally](https://github.com/apexskier/nova-typescript/blob/master/CONTRIBUTING.md#running-locally), but nothing seems to be getting logged to the `.log` output. I might be missing something in the dev setup though.
Wish I could provide more information or context, but I haven't been able to gather much else.
Happy to provide any extra information, or follow debugging steps.

Thanks in advance 🙏

**Comment by alex-ketch** [comment]
Just re-installed Node using [NVM](https://github.com/nvm-sh/nvm) which seems to have fixed the issue.
Not sure if you'd like to keep this issue open to track the problem with asdf. Please feel free to close otherwise, thanks.

**Comment by apexskier** [comment]
I'm hoping this is solved by Nova 1.2. At least one of the potential causes has been resolved, so I'm going to close.

**Comment by benvp** [comment]
Hm I still experience the same issue when using asdf. Since nova 1.2 the extension isn't crashing anymore, but does not really provide any LSP functionality (no code completion, no errors etc.)
